version: "3"

services:
  # Serviço que irá rodar o node
  node:
    # Imagem base do container
    image: node:latest
    # Nome do container para facilitar execução
    container_name: DesafioTecnicoXP
    # Mesmo que `docker run -t`
    tty: true
    # Mesmo que `docker run -i`
    stdin_open: true
    # Substitui o comando padrão da imagem do node
    command: bash
    # Restarta a imagem caso algo a faça parar
    restart: always
    # Diretório padrão de execução
    working_dir: /app
    # Lista de volumes (diretórios) mapeados de fora para dentro do container
    volumes:
      # Monta o diretório atual, com todos os dados do projeto, 
      # dentro do diretório /app
      - ./:/app
    # Lista de serviços do qual este serviço depende
    depends_on:
      # Precisa do banco funcionando antes de subir o node
      - db
    # Lista de portas mapeadas de dentro para fora do container
    # na notação porta_de_fora:porta_de_dentro
    ports:
      # Expõe a porta padrão da aplicação: altere aqui caso use outra porta
      - 3001:3001
    # Configura as variáveis de ambiente dentro do container
    environment:
      JWT_SECRET: senhasecreta
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      MYSQL_PORT: 3001

  # Serviço que irá rodar o banco de dados
  db:
    container_name: DesafioTecnicoXP_db
    image: mysql:8.0.21
    restart: always
    # Lista de portas mapeadas de dentro para fora do container
    # na notação porta_de_fora:porta_de_dentro
    ports:
      # Expõe a porta padrão do banco de dados
      - 3307:3307
      - 33070:33070
    environment:
      MYSQL_ROOT_PASSWORD: password

# As chaves `tty`, `stdin_open` e `command` fazem com que o container fique
# rodando em segundo plano, bem como tornam possível o uso do comando
# `docker attach`, já deixando o terminal atual acoplado ao container, direto
# no bash. Apesar disso, utilizar o attach mais de uma vez irá replicar o
# terminal, portanto é melhor utilizar o comando `docker exec`.
